[Deletion_Management]주요 엔티티 Soft Delete 구현
AirDnS/airDnS-back pull request #128
Opened 2024-01-25 13:11 UTC by parkjihwanKr

- [ ] PaymentException이 없어 해당하는 Exception 추가 후, Merge 에정

2024-01-25 13:55 UTC, hana2set approved these changes
전체적으로 무난한 것 같으나,
스케줄러에서 너무 많은 연관관계가 있는 것 같고, 
있어도 합의에 따라 상관없을 순 있으나 그외에도 너무 많은 로직이 있어서 가독성이 내려간 느낌이 있습니다!
제 개인적인 견해로는, 실제 쿼리 부분을 클래스로 따로 분리해서 처리하는게 괜찮아 보입니다!

2024-01-25 15:19 UTC, hana2set approved these changes

2024-01-26 01:51 UTC, parkjihwanKr commented
> 전체적으로 무난한 것 같으나, 스케줄러에서 너무 많은 연관관계가 있는 것 같고, 있어도 합의에 따라 상관없을 순 있으나 그외에도 너무 많은 로직이 있어서 가독성이 내려간 느낌이 있습니다! 제 개인적인 견해로는, 실제 쿼리 부분을 클래스로 따로 분리해서 처리하는게 괜찮아 보입니다!

2024-01-26 09:23 UTC, hana2set requested changes
전체적으로 무난하게 짜신 것 같습니다!
reject는 첫 부분 타임리프 부분때문에 했구요,
그 외에 첨언을 드리자면, Querydsl 사용부분은, 개인적으로 별도 클래스로 구현하는걸 추천드리긴 합니다.. 종속성이 너무 강해지거든요!

2024-01-26 09:23 UTC, hana2set commented on build.gradle
> +    implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'
뺀거 다시 들어갔어요 ㅠ 머지전에 확인해주셔야됨니다..!
확인하기 어려우시면 개인적으로 sourcetree같은 개발자툴을 이용해서, UI로 확인하시는것도 추천드립니다

2024-01-26 09:36 UTC, parkjihwanKr commented on build.gradle
> +    implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'
1. 타임리프 수정해서 올리겠습니다!
2. QueryDSL은 Class별로 분리하여 추후에 올리겠습니다!

2024-01-27 06:38 UTC, merged