좋아요 API 구현
AirDnS/airDnS-back pull request #14
Opened 2024-01-09 08:19 UTC by parkjihwanKr

- [x] Like 좋아요 구현
- [x] Like 좋아요 취소 구현
- [x] Like 좋아요 Service Test 구현
- [x] Like 좋아요 Controller Test 구현
- [x] Like 좋아요 Repository Test 구현

2024-01-09 09:12 UTC, hana2set reviewed
중복되는 responseEntity의 형태는 다같이 고민해봐야할 부분인 것 같습니다.
new ResponseEntity<>(
                new CommonResponse<>(HttpStatus.CREATED,"룸 좋아요 조회 성공",responseDto),
                HttpStatus.CREATED);
                
의미없는 중복이 많은 것 같습니다

2024-01-09 09:12 UTC, hana2set commented on src/main/java/com/example/airdns/domain/like/controller/LikesController.java
> +                new CommonResponse<>(HttpStatus.OK,"msg",responseDto),
msg가 의미가 없어보이는데 확인해주세요

2024-01-09 09:12 UTC, hana2set commented on src/main/java/com/example/airdns/domain/like/controller/LikesController.java
> +                HttpStatus.OK);
여기도입니다!

2024-01-09 09:12 UTC, hana2set commented on src/main/java/com/example/airdns/domain/like/entity/Likes.java
> +    @ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.PERSIST)
왜 persist만 추가한걸까요?

2024-01-09 09:12 UTC, hana2set commented on src/main/java/com/example/airdns/domain/like/service/LikesServiceImplV1.java
> +    }
1. 개인적으로 postLike라는 단어가 와닿지 않네요.. like한다는 의미인가요?
2. like를 할때 중복된 아이디가 있을때 에러를 낼 필요가 있을까요? 그냥 성공했다고 하는게 맞지 않을까요?

2024-01-09 09:12 UTC, hana2set commented on src/main/java/com/example/airdns/domain/like/service/LikesServiceImplV1.java
> +
여기도 마찬가지입니다! 한번 생각해볼 필요가 있을 것 같습니다

2024-01-09 10:16 UTC, Kim-Jong-Gyu requested changes

2024-01-09 10:16 UTC, Kim-Jong-Gyu commented on src/main/java/com/example/airdns/domain/like/controller/LikesController.java
return에 ResponseEntity<>() 부분을 ResponseEntity.status(HttpStatus.CREATED).body()로 통일하는게 좋을거 같습니다.

2024-01-09 10:16 UTC, Kim-Jong-Gyu commented on src/main/java/com/example/airdns/domain/like/entity/Likes.java
CascadeType.Persist를 추가한 이유를 알 수 있을까요??

2024-01-09 10:16 UTC, Kim-Jong-Gyu commented on src/main/java/com/example/airdns/domain/like/exception/UserNotLikedException.java
LikesException으로 통합하고, LikeExceptionCode로 경우의 수를 다루는게 나을거 같습니다.

2024-01-09 11:47 UTC, Kim-Jong-Gyu approved these changes

2024-01-10 01:12 UTC, hana2set approved these changes

2024-01-10 01:13 UTC, merged