Feat/likes : 룸에 대한 좋아요 구현
AirDnS/airDnS-back pull request #50
Opened 2024-01-17 08:42 UTC by parkjihwanKr

룸에 대한 좋아요 리스트 구현 삭제 -> 룸에 대한 좋아요 구현

2024-01-17 09:07 UTC, Kim-Jong-Gyu requested changes

2024-01-17 09:07 UTC, Kim-Jong-Gyu commented on src/main/java/com/example/airdns/domain/like/controller/LikesController.java
swagger 로 설명이 있어서 따로 주석이 필요 없을거 같습니다.

2024-01-17 09:07 UTC, Kim-Jong-Gyu commented on src/main/java/com/example/airdns/domain/like/service/LikesService.java
주석부분 없애는게 좋을거 같습니다.

2024-01-17 09:07 UTC, Kim-Jong-Gyu commented on src/main/java/com/example/airdns/domain/like/service/LikesServiceImplV1.java
해당 룸에 대한 좋아요 개수만 확인하는 함수 기능을 가지고 있는거 같은데 느낌이 좋아요 한 사람 리스트를 확인하는 로직이라 수정했으면 좋겠습니다. 반환값으로 count만 나와도 될거 같습니다.

2024-01-17 09:07 UTC, hana2set approved these changes
getRoomLike의 함수의 목표성만 정확히 하시고 머지하시면 될것같습니다!
list를 조회하고싶은지 count를 가져오고싶은지 햇갈리네요

2024-01-17 09:07 UTC, hana2set commented on src/main/java/com/example/airdns/domain/like/service/LikesServiceImplV1.java
> +
count를 출력하는 함수가 맞나요? 맞으면 likeCount외에 다른 정보는 의미가 없는 것 같습니다.

2024-01-17 09:08 UTC, parkjihwanKr commented on src/main/java/com/example/airdns/domain/like/service/LikesService.java
넵, 확인했고 주석 없앴습니다!

2024-01-17 09:08 UTC, parkjihwanKr commented on src/main/java/com/example/airdns/domain/like/service/LikesServiceImplV1.java
반환값으로 count값만 반환하게 만들었습니다!

2024-01-18 02:33 UTC, Kim-Jong-Gyu commented on src/main/java/com/example/airdns/domain/like/service/LikesServiceImplV1.java
저희 코딩 컨벤션에 의하면 Get이 아니라 Read가 적절한거 같습니다.

2024-01-18 02:33 UTC, Kim-Jong-Gyu approved these changes

2024-01-18 02:34 UTC, merged