결제 요청 back 구현
AirDnS/airDnS-back pull request #54
Opened 2024-01-17 13:01 UTC by rinyejo

우선 결제 요청 API 구현했습니다. 결제 완료 시 성공, 실패 부분 빠른 시간 내로 구현할 예정입니다.

2024-01-17 13:10 UTC, rinyejo commented
build.gradle implementation 누락으로 오류 발생합니다. merge 하지 마십쇼.

2024-01-17 14:31 UTC, Kim-Jong-Gyu commented on src/main/java/com/example/airdns/domain/payment/controller/PaymentController.java
swagger 적용하셔야 될거 같습니다.

2024-01-17 14:38 UTC, Kim-Jong-Gyu requested changes

2024-01-17 14:38 UTC, Kim-Jong-Gyu commented on src/main/java/com/example/airdns/domain/payment/dto/PaymentResponseDto.java
> +    public PaymentResponseDto toPaymentResponseDto() {
DB에 저장될 결제 관련 정보인데 클래스 명이 Dto보다는 toEntity가 더 적절해 보입니다. 그리고 ResponseDto에 저장될 결제 관련 정보를 구현 하신 이유가 있으신가요?

2024-01-17 14:40 UTC, Kim-Jong-Gyu commented on src/main/java/com/example/airdns/domain/payment/dto/PaymentResponseDto.java
> +    public PaymentResponseDto toPaymentResponseDto() {
그리고 저희 CodeConvention을 보면, Dto관련 클래스명이 있는데 규칙에 맞게 수정하는 것이 좋을거 같습니다.

2024-01-17 14:40 UTC, Kim-Jong-Gyu commented on src/main/java/com/example/airdns/domain/payment/dto/PaymentResponseDto.java
> +    public PaymentResponseDto toPaymentResponseDto() {
어려운 부분하느라 수고하셨습니다!!!

2024-01-17 14:58 UTC, hana2set approved these changes
코드 스타일적으로는 크게 문제가 없어 보입니다!
그 외 제가 적은 부분에 수정하실 내용이 있으시면 수정하시고 올리시면 될 것 같습니다..!
머지가 우선시되면 올리고 issue로 관리해주시면 더 좋을 것 같습니다!

2024-01-17 14:58 UTC, hana2set commented on src/main/java/com/example/airdns/domain/payment/service/PaymentServiceImplV1.java
> +            return "Reservation Not Found";
requestPayment에서 예약 ID가 없을경우,
status : 200,
message : reservation not found
인것같은데 의도된 부분일까요?

에러로 처리해야되는 느낌인데요 ( 예약이 없으면 결제가 되면 안됨으로..)

optional 객체를 받아 처리할 필요 없이, optional을 풀면서 에러처리 후 
reservation을 사용하면 되지 않나 싶네요!
구체적으로
findById(reservationId).orElseThrow(() -> new CustomException()); 

이런느낌이요!

2024-01-17 14:58 UTC, hana2set commented on src/main/java/com/example/airdns/domain/payment/service/PaymentServiceImplV1.java
>      }
base64 처리하신 이유가 있을까요?
어떤 로직인지는 확실하지 않으나,
base64는 암호화 라기보다 난독화 쪽에 가깝다고 생각해서
어떤 곳에 쓰이냐에따라 의미 없는 내용인 것 같아서요!
난독화만 생각하신거라면 그냥 넘어가셔도됩니다!

2024-01-17 14:58 UTC, hana2set commented on src/main/java/com/example/airdns/domain/payment/dto/PaymentResponseDto.java
> +                .createdAt(String.valueOf(getCreatedAt()))
이친구 혼자만 valueOf로 넣으신 이유가 있을까요?!

2024-01-18 03:13 UTC, rinyejo commented on src/main/java/com/example/airdns/domain/payment/service/PaymentServiceImplV1.java
>      }
이 부분은 해당 PG사의 공식 문서에 명시된 내용입니다!

2024-01-19 17:48 UTC, merged